
[theme]
primaryColor = "#1DB954"               # Spotify Green
backgroundColor = "#191414"            # Spotify Black
secondaryBackgroundColor = "#1ED760"   # Spotify Light Green
textColor = "#FFFFFF"                  # White text
font = "sans serif"


[server]
headless = true
enableCORS = false
port = 8501

[client]
showErrorDetails = true


