[theme]
primaryColor = "#0B5394"         # Deep blue (brand/confidence)
backgroundColor = "#F8F9FA"      # Very light grey (clean background)
secondaryBackgroundColor = "#E0E7EF"  # Soft blue-gray (panel areas)
textColor = "#1C1C1C"            # Dark gray-black for readability
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501

[client]
showErrorDetails = true


