# .streamlit/config.toml

[theme]
primaryColor = "#0B5394"               # Accent color (kept)
backgroundColor = "#1E1E2F"            # Dark slate background
secondaryBackgroundColor = "#2A2A3E"   # Slightly lighter panels
textColor = "#E0E0E0"                  # Light grey text for readability
font = "system-ui"




[server]
headless = true
enableCORS = false
port = 8501

[client]
showErrorDetails = true


